#!/usr/bin/env node
/**
 * KISA 이론(MCQ) 문제 pool 확장 — 구현 챕터 각 2문제씩 생성.
 * REBUILD16 §10 Stage 3 (R4) — scripts/seed/ 표준 위치로 이전, 공통 헬퍼 사용.
 *
 * 각 챕터의 취약점에 대해 두 관점으로 MCQ 2개를 생성한다:
 *   Q1: "원인·원리 설명 중 옳지 않은 것은?" — 4개 중 1개가 틀린 설명
 *   Q2: "방어 방법 중 옳은 것은?"         — 4개 중 1개가 옳은 방법
 *
 * 출력: kisa-module/seed/mcq-extra-questions.json ({questions:[...]})
 * 사용법: node scripts/seed/kisa-mcq.js
 * 적용: psql 로 UPSERT (weakness_code 는 {chapter_code}-MCQ-X-{A|B})
 */
const { shuffleKeep, writeSeedJson } = require('./_utils');

// [chapter_code, category, language, name, concept_correct_list, concept_wrong, defense_correct, defense_wrong_list]
// concept_correct: 3개 (정답 아닌 맞는 설명), concept_wrong: 1개 (Q1 정답 = 틀린 설명)
// defense_correct: 1개 (Q2 정답 = 옳은 방어), defense_wrong: 3개 (오답)
const TOPICS = [
  // === IMP-AA 오용 ===
  ['IMP-AA-01','api_abuse','java','DNS lookup에 의존한 보안결정',
    ['IP 역조회 결과는 DNS 스푸핑·캐시 포이즈닝으로 변조될 수 있다.',
     '호스트명 기반 ACL 만으로는 신원 보장이 불가능하다.',
     'TLS 상호 인증(mTLS) 은 DNS 가 아닌 인증서 체인으로 신원 확인한다.'],
    'reverse DNS lookup 결과는 변조 불가능해 신뢰할 수 있다.',
    'TLS 클라이언트 인증서 검증 기반 상호 인증을 적용한다.',
    ['IP 주소 정규식으로 화이트리스트를 관리한다.',
     'User-Agent 헤더를 검사해 차단한다.',
     'Reverse DNS 결과를 신뢰해 권한을 판단한다.']],
  ['IMP-AA-02','api_abuse','java','취약한 API 사용',
    ['String.getBytes() 는 플랫폼 기본 문자셋을 사용한다.',
     'new String(byte[]) 역시 인코딩 지정 없으면 환경 의존적이다.',
     '해시·암호·파일 I/O 등은 항상 명시적 인코딩(UTF-8)을 지정해야 한다.'],
    '플랫폼 기본 문자셋은 모든 JDK 에서 동일해 안전하다.',
    'StandardCharsets.UTF_8 을 명시적으로 지정한다.',
    ['Charset.defaultCharset() 으로 자동 선택한다.',
     'System.getProperty("file.encoding") 을 읽어 사용한다.',
     '인코딩을 지정하지 않고 JVM 기본값에 맡긴다.']],

  // === IMP-CE 코드오류 ===
  ['IMP-CE-01','code_error','java','Null Pointer 역참조',
    ['null 상태에서 .메소드() 호출 시 NullPointerException 이 발생한다.',
     'Optional 은 값이 null 일 때를 안전하게 래핑한다.',
     '공용 API 경계에서는 Objects.requireNonNull 로 계약을 명시한다.'],
    'null 검사는 런타임 비용이 커서 생략하는 것이 성능상 유리하다.',
    'Optional.ofNullable(x).ifPresent(...) 패턴으로 처리한다.',
    ['try-catch(NullPointerException) 로 감싸서 무시한다.',
     '모든 변수를 String 으로 초기화한다.',
     'assert 문으로 처리하고 프로덕션에서는 끈다.']],
  ['IMP-CE-02','code_error','java','부적절한 자원 해제',
    ['InputStream, Connection, Socket 등은 사용 후 반드시 close() 해야 한다.',
     'try-with-resources 는 AutoCloseable 자원을 자동 해제한다.',
     'finally 블록은 예외 발생 시에도 자원 해제를 보장한다.'],
    'Java 는 GC 가 있으므로 stream, connection 을 명시적으로 닫을 필요가 없다.',
    'try-with-resources 구문으로 선언부에서 자동 해제한다.',
    ['finalize() 메소드에 해제 로직을 작성한다.',
     'System.gc() 를 호출해 강제 정리한다.',
     'connection pool 이 알아서 처리하도록 둔다.']],
  ['IMP-CE-03','code_error','etc','해제된 자원 사용',
    ['free() 된 메모리 포인터 재사용은 Use-After-Free(UAF) 로 불린다.',
     'UAF 는 heap spray 와 결합해 RCE 로 이어질 수 있다.',
     '해제 직후 포인터에 NULL 대입이 기본 방어다.'],
    'free() 후에도 포인터는 동일 메모리를 가리키므로 재사용해도 안전하다.',
    '해제 직후 NULL 대입 + 스마트 포인터(unique_ptr) 사용.',
    ['free() 를 두 번 호출해 메모리를 초기화한다.',
     '전역 배열에 모든 포인터를 저장한다.',
     'ASLR 이 있으니 UAF 는 익스플로잇되지 않는다.']],
  ['IMP-CE-04','code_error','etc','초기화되지 않은 변수 사용',
    ['C/C++ 의 스택 변수는 자동 초기화되지 않는다.',
     '초기화 없이 읽으면 이전 함수의 잔재 값이 노출될 수 있다.',
     'calloc 은 할당된 메모리를 0 으로 초기화한다.'],
    'malloc 은 항상 0 으로 초기화된 메모리를 반환한다.',
    '모든 지역 변수는 선언 즉시 0 이나 기본값으로 초기화한다.',
    ['변수를 사용 직전에 선언하면 초기화 불필요하다.',
     'volatile 키워드를 붙이면 자동 초기화된다.',
     'memcmp 로 읽기 전에 0 인지만 확인하면 안전하다.']],
  ['IMP-CE-05','code_error','java','신뢰할 수 없는 데이터의 역직렬화',
    ['Java ObjectInputStream.readObject() 는 임의 클래스 인스턴스를 생성한다.',
     '가젯 체인을 이용하면 역직렬화만으로 RCE 가능하다.',
     'JSON/Jackson 도 @JsonTypeInfo 남용 시 동일 위험이 있다.'],
    '직렬화된 바이트에는 실행 코드가 없으므로 역직렬화는 항상 안전하다.',
    'ObjectInputFilter 로 허용 클래스 화이트리스트를 적용한다.',
    ['입력 바이트 앞 4바이트만 검증한다.',
     'try-catch 로 감싸서 예외를 무시한다.',
     'Base64 로 인코딩 후 저장하면 안전하다.']],

  // === IMP-EH 에러처리 ===
  ['IMP-EH-01','error_handling','java','오류 메시지 정보노출',
    ['스택트레이스에 SQL 구문·파일 경로·버전이 노출될 수 있다.',
     '공격자는 오류 메시지로 내부 구조를 정찰한다.',
     '프로덕션에서는 일반화된 메시지만 노출해야 한다.'],
    '상세 오류 메시지는 사용자 경험을 위해 항상 모든 정보를 공개해야 한다.',
    '사용자에겐 일반 메시지, 서버 로그에만 상세 내용을 기록한다.',
    ['스택트레이스를 모두 API 응답에 포함한다.',
     'HTTP 500 대신 200 으로 반환해 에러 자체를 숨긴다.',
     '에러 발생 시 어떤 로그도 남기지 않는다.']],
  ['IMP-EH-02','error_handling','java','오류상황 대응 부재',
    ['예외가 발생해도 자원은 finally 나 try-with-resources 로 해제한다.',
     '부분적 상태 변경이 발생했다면 롤백해야 일관성이 유지된다.',
     '무시된 예외는 장애 원인 추적을 어렵게 만든다.'],
    '빈 catch 블록으로 예외를 삼키는 것이 가장 우아한 처리 방식이다.',
    'catch 에서 로깅 + 필요 시 rethrow, finally 에서 자원 해제.',
    ['모든 예외를 Exception 으로 잡아 로그만 남기고 무시한다.',
     '예외를 throws 선언 없이 전역으로 전파시킨다.',
     '예외 발생 시 System.exit(1) 로 종료한다.']],
  ['IMP-EH-03','error_handling','java','부적절한 예외 처리',
    ['구체적 예외보다 Exception 을 잡으면 원인 식별이 어려워진다.',
     'rethrow 없는 catch 는 호출자에게 실패를 숨기는 꼴이 된다.',
     '로그에는 예외 메시지뿐 아니라 스택트레이스도 포함해야 한다.'],
    'catch(Exception e) {} 처럼 모든 예외를 조용히 삼키는 것이 안정성을 높인다.',
    '의미 있는 로그 + 재전파 여부 명확히 판단 + 자원 정리 finally.',
    ['모든 메소드에 throws Throwable 을 붙여 둔다.',
     'catch 에서 e.printStackTrace() 만 호출하고 끝낸다.',
     'exception chaining 을 사용하지 않고 새 예외만 던진다.']],

  // === IMP-EN 캡슐화 ===
  ['IMP-EN-01','encapsulation','java','잘못된 세션에 의한 데이터 정보 노출',
    ['서블릿에서 static 변수에 요청별 데이터를 저장하면 동시 요청이 공유한다.',
     'ThreadLocal 은 사용 후 반드시 remove 해야 누수가 없다.',
     '@RequestScope / @SessionScope 빈으로 범위를 명확히 한다.'],
    'static 변수는 요청마다 독립적으로 저장되어 사용자 분리가 자동 보장된다.',
    '요청 스코프 객체(@RequestScope)나 메소드 로컬 변수를 사용한다.',
    ['HttpServletRequest 를 static 필드에 저장해 재사용한다.',
     'synchronized 블록 하나로 모든 동시성 문제를 해결한다.',
     '모든 필드를 public static 으로 선언해 공유한다.']],
  ['IMP-EN-02','encapsulation','java','제거되지 않고 남은 디버그 코드',
    ['System.out.println, console.log 는 운영 환경에서도 계속 출력된다.',
     '배포 번들에 소스맵이 남으면 원본 코드가 노출된다.',
     '개발자 계정 하드코딩, 테스트 URL 잔존은 대표적 실수다.'],
    '개발자만 보는 console.log 는 보안에 영향이 없어 제거할 필요가 없다.',
    '프로파일 분리 + 빌드 시 디버그 코드 제거(소스맵 분리) 적용.',
    ['디버그 로그는 모두 DEBUG 레벨이므로 프로덕션에선 자동 사라진다.',
     '클라이언트 JS 는 난독화되므로 그대로 두어도 안전하다.',
     '주석으로 처리된 코드는 브라우저에 로드되지 않는다.']],
  ['IMP-EN-03','encapsulation','java','Public 메소드부터 반환된 Private 배열',
    ['배열은 참조 타입이므로 반환 시 호출자가 원본을 수정 가능하다.',
     '불변 컬렉션(Collections.unmodifiableList) 으로 감싸면 방어된다.',
     'Arrays.copyOf 로 깊은 복사본을 반환하면 원본이 보호된다.'],
    'private 필드이기만 하면 반환된 참조도 외부에서 수정 불가능하다.',
    'Arrays.copyOf() 로 복사본을 반환한다.',
    ['배열을 final 로 선언하면 원소 수정도 금지된다.',
     '@Nullable 어노테이션을 붙이면 된다.',
     '반환 타입을 Object 로 선언해 캐스팅을 막는다.']],
  ['IMP-EN-04','encapsulation','java','Private 배열에 Public 데이터 할당',
    ['setter 가 외부 배열 참조를 그대로 저장하면 외부 수정이 내부에 반영된다.',
     'defensive copy 로 수신 데이터를 복사 저장해야 캡슐화가 유지된다.',
     '불변 객체 패턴에서는 내부 상태 변경을 완전히 차단한다.'],
    'setter 는 참조만 저장하므로 외부 변경은 내부에 반영되지 않는다.',
    'setter 에서 Arrays.copyOf() 로 깊은 복사 후 저장한다.',
    ['참조만 저장하고 외부에서 수정하지 않도록 문서로 공지한다.',
     'synchronized setter 로 감싸면 해결된다.',
     'volatile 키워드를 배열에 붙인다.']],

  // === IMP-IV 입력검증 (핵심 17개) ===
  ['IMP-IV-01','input_validation','java','SQL 삽입',
    ['PreparedStatement 는 SQL 구조와 데이터를 분리해 바인딩한다.',
     'MyBatis 의 #{} 는 바인드, ${} 는 문자열 치환이다.',
     'ORM 을 써도 동적 쿼리 구성에서 SQL 삽입이 발생할 수 있다.'],
    '입력값을 URL 인코딩하면 SQL 삽입이 완전히 방어된다.',
    'PreparedStatement + ? 바인드 파라미터 사용.',
    ['SELECT 문은 SQL 삽입이 불가능하다.',
     'LIMIT, ORDER BY 절에는 바인드 파라미터가 필요 없다.',
     'ESCAPE 절만 추가하면 모든 특수문자가 처리된다.']],
  ['IMP-IV-02','input_validation','javascript','코드 삽입',
    ['eval(userInput) 은 임의 JS 실행으로 이어진다.',
     'Function(str) 도 eval 과 동일한 위험이 있다.',
     '서버 사이드 템플릿의 SSTI 는 RCE 로 이어질 수 있다.'],
    'setTimeout(fn, 0) 은 eval 과 같은 방식으로 사용해도 안전하다.',
    'JSON.parse 같은 안전한 파서 사용 + 템플릿은 이스케이프 모드.',
    ['eval 대신 new Function() 을 쓰면 안전하다.',
     '사용자 입력을 Base64 로 인코딩 후 eval 하면 안전하다.',
     '클라이언트에서 실행되므로 서버엔 영향 없다.']],
  ['IMP-IV-03','input_validation','java','경로 조작 및 자원 삽입',
    ['".." 가 포함된 경로는 상위 디렉토리로 이동 가능하다.',
     'getCanonicalPath 는 심볼릭 링크를 해석해 실제 경로를 반환한다.',
     '허용 루트 디렉토리로 시작하는지 startsWith 검증이 필요하다.'],
    'replace("../", "") 한 번이면 경로 조작이 완벽히 차단된다.',
    'File.getCanonicalPath() 후 허용 루트와 startsWith 비교.',
    ['URL 인코딩된 %2e%2e 는 파일 시스템에서 무시된다.',
     '파일명을 고정 접두사로 감싸면 자동 방어된다.',
     '상위 경로 이동은 운영체제 레벨에서 차단된다.']],
  ['IMP-IV-04','input_validation','java','크로스사이트 스크립트',
    ['DOM 기반 XSS 는 서버 응답에 포함되지 않는 클라이언트 전용 변형이다.',
     'HTML 속성, JS, URL, CSS 컨텍스트마다 이스케이프 규칙이 다르다.',
     'Content-Security-Policy 헤더는 XSS 영향 완화에 효과적이다.'],
    'innerText 대신 innerHTML 을 쓰면 XSS 가 차단된다.',
    '출력 컨텍스트별 이스케이프(HtmlUtils.htmlEscape 등) + CSP.',
    ['htmlspecialchars 한 번이면 모든 XSS 가 차단된다.',
     '모든 입력에 strip_tags 만 적용하면 된다.',
     'HTTPS 만 사용하면 XSS 는 일어나지 않는다.']],
  ['IMP-IV-05','input_validation','java','운영체제 명령어 삽입',
    ['Runtime.exec(String) 은 셸 메타문자 ; | & 로 주입이 가능하다.',
     'ProcessBuilder 인자 배열은 셸 해석을 거치지 않는다.',
     '최소 권한 계정 + chroot 환경이 다층 방어에 기여한다.'],
    '명령어 앞에 "safe_" 접두사를 붙이면 모든 삽입이 차단된다.',
    'ProcessBuilder 에 인자를 배열로 전달하고 화이트리스트 검증.',
    ['Runtime.exec(String[]) 이면 어떤 입력이든 그대로 안전하다.',
     'Windows 환경에서는 OS 명령어 삽입이 발생하지 않는다.',
     'sudo 권한 없이 실행하면 임의 명령은 성공하지 않는다.']],
  ['IMP-IV-06','input_validation','java','위험한 형식 파일 업로드',
    ['.jsp, .php 같은 실행 가능 확장자가 업로드 디렉토리에 저장되면 웹쉘 위험.',
     '파일 시그니처(magic number) 검증이 확장자보다 신뢰도가 높다.',
     '업로드 디렉토리에서 스크립트 실행 권한 제거가 기본 대책이다.'],
    '확장자를 소문자로 바꾸면 위험한 확장자 판별이 완벽히 된다.',
    'magic number 검증 + 실행 권한 제거 + 별도 저장 위치.',
    ['원본 파일명을 그대로 저장해 추적성을 확보한다.',
     'Content-Type 헤더를 신뢰해 파일 타입을 판정한다.',
     '업로드 후 즉시 서버에서 실행해 이상 여부를 본다.']],
  ['IMP-IV-07','input_validation','java','신뢰되지 않는 URL 주소로 자동접속 연결',
    ['redirect 파라미터가 외부 사이트를 가리키면 피싱에 악용된다.',
     'Open Redirect 는 OAuth redirect_uri 검증 우회와 결합될 수 있다.',
     '상대 경로만 허용해도 // 접두사를 통한 프로토콜 상대 우회가 가능하다.'],
    '리다이렉트 URL 앞에 "/" 문자가 있으면 외부 이동이 불가능하다.',
    '서버 측 allowlist(도메인 목록) 로 리다이렉트 대상 제한.',
    ['http:// 접두사만 제거하면 외부 이동이 차단된다.',
     'JavaScript 에서 window.location 을 바꾸면 안전하다.',
     'HTTP 302 대신 HTML <meta refresh> 를 쓰면 안전하다.']],
  ['IMP-IV-08','input_validation','java','부적절한 XML 외부 개체 참조',
    ['XXE 는 외부 엔티티 해석으로 로컬 파일 유출·SSRF 를 일으킨다.',
     'Billion Laughs(Entity Expansion) 는 DoS 변형 공격이다.',
     'DocumentBuilderFactory FEATURE_SECURE_PROCESSING 이 기본 방어다.'],
    '잘 구성된(well-formed) XML 이면 XXE 는 발생하지 않는다.',
    'disallow-doctype-decl=true 설정 + FEATURE_SECURE_PROCESSING.',
    ['XML 파일을 UTF-8 로 파싱하면 XXE 가 차단된다.',
     'XML 스키마(XSD) 검증만으로 외부 엔티티가 차단된다.',
     'SAXParser 는 기본적으로 XXE 에 안전하다.']],
  ['IMP-IV-09','input_validation','java','XML 삽입',
    ['사용자 입력이 XML 태그/속성 구조에 삽입되면 파싱이 변조된다.',
     '< > & " \' 다섯 문자가 핵심 이스케이프 대상이다.',
     'DOM API 로 요소·속성을 명시적으로 생성하면 구조 변조가 없다.'],
    'Base64 로 감싸면 XML 삽입은 원천 차단된다.',
    'DOM API 로 구조 생성 + 문자 데이터는 createTextNode 사용.',
    ['XML 은 HTML 과 달리 삽입 공격에 영향받지 않는다.',
     'CDATA 섹션으로 감싸면 모든 입력이 안전하다.',
     'XML 선언부(<?xml?>) 만 검증하면 충분하다.']],
  ['IMP-IV-10','input_validation','java','LDAP 삽입',
    ['LDAP 필터 특수문자 *, (, ), \\, NUL 이 주입 벡터다.',
     'RFC 4515 준수 라이브러리의 encodeForLDAP 이 안전한 이스케이프를 제공한다.',
     '인증 시 사용자 입력을 그대로 필터에 결합하면 인증 우회가 가능하다.'],
    'LDAP 은 인증 프로토콜이라 삽입 공격이 발생하지 않는다.',
    '특수문자를 \\xx 헥사 이스케이프 + 라이브러리 사용.',
    ['비밀번호를 MD5 해시로 넘기면 LDAP 삽입이 차단된다.',
     'SASL 인증을 쓰면 LDAP 삽입이 발생하지 않는다.',
     '필터 문자열에 괄호가 없으면 삽입 불가하다.']],
  ['IMP-IV-11','input_validation','java','크로스사이트 요청 위조',
    ['CSRF 는 세션 쿠키의 자동 전송을 악용한다.',
     'SameSite=Strict 쿠키 속성은 교차 사이트 전송을 차단한다.',
     'Synchronizer Token Pattern 은 요청당 토큰을 검증한다.'],
    'POST 요청은 기본적으로 CSRF 공격 대상이 되지 않는다.',
    'Spring Security CsrfFilter + SameSite 쿠키 + Origin/Referer 검증.',
    ['CORS 헤더만 설정하면 CSRF 가 차단된다.',
     '로그인 후 세션 타임아웃을 짧게 하면 CSRF 가 불가능하다.',
     'HTTPS 만 쓰면 CSRF 공격은 일어나지 않는다.']],
  ['IMP-IV-12','input_validation','java','서버사이드 요청 위조',
    ['SSRF 는 서버가 외부 URL 을 입력 그대로 호출할 때 발생한다.',
     '클라우드 메타데이터 IP(169.254.169.254) 접근이 주요 공격 목표다.',
     'DNS 재조회로 allowlist 를 우회하는 DNS rebinding 도 고려해야 한다.'],
    'HTTPS URL 만 허용하면 SSRF 는 완전히 차단된다.',
    '대상 도메인 allowlist + private IP 차단 + 해석된 IP 검증.',
    ['301 redirect 는 서버가 따라가지 않으니 SSRF 는 불가능하다.',
     '요청 timeout 을 1초로 짧게 두면 SSRF 가 방어된다.',
     '서버 IP 와 다른 IP 는 모두 안전하다고 간주한다.']],
  ['IMP-IV-13','input_validation','java','HTTP 응답분할',
    ['CR(0x0D), LF(0x0A) 가 헤더 값에 포함되면 응답분할이 발생한다.',
     '캐시 포이즈닝 등 추가 공격과 결합될 수 있다.',
     '최신 서블릿 컨테이너는 개행문자 포함 헤더 설정을 거부한다.'],
    '응답분할은 HTTP/2 에서도 기존과 동일한 방식으로 작동한다.',
    '헤더 값 작성 전 CR/LF/탭 문자 제거 또는 요청 거부.',
    ['HTTP 헤더는 항상 ASCII 만 사용되므로 주입 불가능하다.',
     '쿠키 값은 별도로 UTF-8 인코딩되어 안전하다.',
     '브라우저가 알아서 이중 개행을 처리한다.']],
  ['IMP-IV-14','input_validation','etc','정수형 오버플로우',
    ['Integer overflow 는 연산 결과가 표현 범위를 벗어나 래핑되는 현상이다.',
     '음수가 양수로 변하면서 길이 검증을 우회할 수 있다.',
     'C23 ckd_mul, GCC __builtin_mul_overflow 로 체크 가능하다.'],
    'signed int 오버플로우는 C 표준에 의해 0 으로 초기화된다.',
    '연산 전 overflow 체크 매크로 사용 + 상한 검증.',
    ['unsigned int 는 오버플로우가 일어나지 않는다.',
     '변수를 long 으로 선언하면 모든 오버플로우가 방지된다.',
     'try-catch(ArithmeticException) 으로 잡으면 된다.']],
  ['IMP-IV-15','input_validation','java','보안기능 결정에 사용되는 부적절한 입력값',
    ['hidden input, 쿠키 값은 클라이언트가 변조 가능하다.',
     '권한 결정은 서버 세션/토큰 기반으로만 해야 한다.',
     '서버 측 재검증 없는 "1회 확인"은 TOCTOU 와 결합된다.'],
    '클라이언트 JWT 의 alg 필드는 서버가 신뢰해도 무방하다.',
    '서버 측 세션/토큰으로 권한 확인 + 모든 보안 결정 재검증.',
    ['관리자 여부는 사용자 이메일의 도메인으로 결정한다.',
     'hidden 필드 값을 암호화하면 변조 걱정이 없다.',
     'localStorage 에 role 을 저장해 권한을 판정한다.']],
  ['IMP-IV-16','input_validation','etc','메모리 버퍼 오버플로우',
    ['strcpy, sprintf 는 크기 검사 없는 대표적 위험 함수다.',
     'Stack canary, ASLR, DEP 는 완화(mitigation) 기술이다.',
     '크기 제한 함수 strncpy, snprintf 가 기본 대체 수단이다.'],
    'ASLR 이 적용된 현대 OS 에서는 버퍼 오버플로우가 발생하지 않는다.',
    '크기 제한 함수 + 경계 검증 + 컴파일러 보호 옵션.',
    ['gets() 는 표준 함수이므로 사용해도 안전하다.',
     '스택 오버플로우는 GC 언어에서는 발생하지 않는다.',
     'strcpy_s 는 Windows 에서만 동작하므로 Linux 에선 strcpy 를 그대로 쓴다.']],
  ['IMP-IV-17','input_validation','etc','포맷 스트링 삽입',
    ['printf(userInput) 은 %s, %n 시퀀스로 메모리 읽기/쓰기가 가능하다.',
     'printf 의 %n 은 현재까지 출력한 바이트 수를 인자에 쓴다.',
     '포맷 문자열은 항상 상수 리터럴을 사용해야 한다.'],
    'printf 는 가변 인자 함수이므로 추가 인자를 넘기지 않으면 안전하다.',
    'printf("%s", userInput) 처럼 고정 포맷 + 값을 가변인자로 분리.',
    ['snprintf 를 쓰면 포맷 문자열 삽입 공격이 불가능하다.',
     '사용자 입력에 \\n 을 제거하면 %n 공격이 차단된다.',
     '콘솔 출력에는 포맷 스트링 공격이 영향을 주지 않는다.']],

  // === IMP-SF 보안기능 ===
  ['IMP-SF-01','security_feature','java','적절한 인증 없는 중요기능 허용',
    ['관리자 기능은 인증 + 인가 이중 검증이 필요하다.',
     'API 게이트웨이에서 모든 경로에 대해 기본 정책을 적용한다.',
     'Spring Security @PreAuthorize 는 메소드 수준 권한 검사를 제공한다.'],
    '중요 기능은 URL 만 숨기면 인증 없이 공개되어도 안전하다.',
    '모든 중요 기능에 인증 필터 + 메소드 수준 권한 검사 적용.',
    ['HTTP Referer 헤더로 관리자 페이지 접근을 판단한다.',
     'User-Agent 가 특정 값이면 자동 로그인 처리한다.',
     '내부망에서만 접근 가능하다고 가정하고 인증을 생략한다.']],
  ['IMP-SF-04','security_feature','java','취약한 암호화 알고리즘 사용',
    ['DES, 3DES, RC4 는 더 이상 안전하지 않다.',
     'MD5, SHA-1 은 충돌 공격으로 무결성 보장이 깨졌다.',
     'AES-256, ChaCha20, SHA-256 이상 사용이 권장된다.'],
    'MD5 는 빠르기 때문에 비밀번호 해시로 권장된다.',
    'AES-GCM, ChaCha20-Poly1305 같은 인증 암호화 사용.',
    ['3DES 는 DES 를 3번 쓰므로 AES-256 과 같은 수준이다.',
     '알고리즘보다 키 길이만 늘리면 안전하다.',
     '내부 통신은 ROT13 으로 암호화해도 충분하다.']],
  ['IMP-SF-06','security_feature','java','하드코드된 중요정보',
    ['소스 주석, 설정 파일에 비밀키가 그대로 남으면 저장소 유출 시 치명적이다.',
     'KMS, Secrets Manager, Vault 같은 전용 저장소가 표준 해법이다.',
     '환경변수 주입은 최소한 소스 분리는 달성한다.'],
    '소스에 키를 박되 Base64 로 인코딩하면 하드코딩 취약점이 해결된다.',
    'Secret Manager/KMS 에 저장 후 환경변수나 SDK 로 주입.',
    ['키를 주석으로 감춰두면 빌드 산출물에 포함되지 않는다.',
     '비밀번호를 reverse() 함수로 뒤집어 저장한다.',
     'Git ignore 에 키 파일을 등록하면 안전하다.']],
  ['IMP-SF-08','security_feature','java','적절하지 않은 난수값 사용',
    ['java.util.Random 은 선형 합동 PRNG 로 예측 가능하다.',
     'System.currentTimeMillis() 기반 시드는 재현 가능해 보안에 부적합하다.',
     'java.security.SecureRandom 은 /dev/urandom 등 엔트로피 소스를 사용한다.'],
    'Math.random() 은 내부적으로 SecureRandom 을 사용해 보안에 안전하다.',
    'SecureRandom 또는 JDK 17+ RandomGenerator(secure variant) 사용.',
    ['UUID.randomUUID() 는 난수가 아니라 결정론적이므로 안전하다.',
     'Random 에 System.nanoTime() 을 시드로 주면 예측 불가능해진다.',
     'Random 을 static 으로 선언하면 예측이 어려워진다.']],
  ['IMP-SF-02','security_feature','java','부적절한 인가',
    ['역할 검증만으로는 리소스 소유자 권한을 확인할 수 없다.',
     'IDOR(Insecure Direct Object Reference) 이 대표 사례다.',
     '요청마다 자원 소유자와 현재 사용자 ID 비교가 필요하다.'],
    '인증된 사용자이면 어떤 자원이든 접근 가능하게 열어도 된다.',
    '리소스 단위 인가 검사 + 소유자 ID 비교.',
    ['URL 에 userId 가 있으면 알아서 검증된다.',
     'role=admin 쿠키만 확인하면 충분하다.',
     '프런트엔드에서 권한별 UI 만 숨기면 된다.']],
  ['IMP-SF-03','security_feature','java','중요한 자원에 대한 잘못된 권한 설정',
    ['파일 권한 777 은 누구나 읽기/쓰기/실행 가능한 상태다.',
     '최소 권한 원칙(PoLP)을 따라 필요한 만큼만 부여한다.',
     'umask 설정으로 신규 생성 파일의 기본 권한을 제한한다.'],
    '모든 파일을 777 로 두면 배포 오류가 없어 운영상 권장된다.',
    'chmod 600 (또는 640) + umask 027 로 최소 권한 적용.',
    ['chmod 755 가 보안 설정의 표준이다.',
     '컨테이너 내부는 격리되므로 root 로 실행해도 안전하다.',
     '권한은 애플리케이션 코드에서 동적으로 변경한다.']],
  ['IMP-SF-05','security_feature','java','암호화되지 않은 중요정보',
    ['DB 저장 정보도 유출 대비 암호화가 필요하다.',
     '전송 구간은 TLS, 저장 구간은 AES-GCM 같은 인증 암호화가 기본.',
     '키는 데이터와 분리 보관(KMS, Vault)해야 유출 시 피해가 제한된다.'],
    'HTTPS 만 쓰면 DB 에 평문 저장해도 안전하다.',
    '저장=AES-GCM 인증 암호화, 전송=TLS 1.2+, 키=KMS 에 분리.',
    ['Base64 인코딩은 암호화의 일종이므로 충분하다.',
     '비밀번호는 reverse() 후 저장하면 복호화 불가능해 안전하다.',
     '내부 DB 는 외부 접근 불가하므로 평문 저장 가능하다.']],
  ['IMP-SF-09','security_feature','java','취약한 비밀번호 허용',
    ['사전 공격(dictionary attack)은 유출된 비밀번호 목록을 이용한다.',
     '길이·복잡도·유출 단어 필터링이 표준이다.',
     'HaveIBeenPwned 같은 외부 API 로 유출 여부를 확인할 수 있다.'],
    '4자리 숫자 PIN 은 충분히 안전하다.',
    '길이 8 자 이상 + 복잡도 + 유출 목록 대조.',
    ['사용자 이름과 다르면 어떤 비밀번호든 허용한다.',
     '특수문자만 포함하면 무조건 안전하다.',
     '관리자가 수동으로 확인하는 것이 가장 안전하다.']],
  ['IMP-SF-12','security_feature','java','사용자 하드디스크에 저장되는 쿠키를 통한 정보 노출',
    ['Max-Age/Expires 가 있는 쿠키는 브라우저 종료 후에도 파일로 남는다.',
     '공유 PC 에서 쿠키 탈취로 세션 유출이 일어날 수 있다.',
     'HttpOnly + Secure + SameSite 조합이 표준 방어다.'],
    '세션 쿠키에 Max-Age=31536000 을 주면 로그인이 편리해져 보안에 유리하다.',
    '세션 쿠키는 Max-Age/Expires 없이 + HttpOnly + Secure + SameSite.',
    ['쿠키 값을 URL 인코딩하면 디스크에 평문으로 저장되지 않는다.',
     'HTTPS 쿠키는 디스크에 저장되지 않는다.',
     '쿠키 이름에 _secure 접미사를 붙이면 방어된다.']],
  ['IMP-SF-13','security_feature','java','주석문 안에 포함된 시스템 주요정보',
    ['JS 번들의 주석은 브라우저에 그대로 노출된다.',
     'minify 단계에서 주석 제거가 표준이다.',
     '개발자 계정·테스트 URL 잔존은 전형적 실수다.'],
    '주석은 실행되지 않으므로 비밀정보를 남겨도 안전하다.',
    '빌드 시 주석 제거 + 민감 정보 ESLint 규칙으로 사전 차단.',
    ['주석에 // SECRET 을 붙이면 배포 시 자동 제거된다.',
     '서버 렌더링 템플릿의 주석은 클라이언트에 가지 않는다.',
     'git blame 으로 찾을 수 없으면 안전하다.']],
  ['IMP-SF-14','security_feature','java','솔트 없이 일방향 해시함수 사용',
    ['MD5/SHA-1 만으로는 레인보우 테이블 역추적에 노출된다.',
     '솔트는 사용자마다 고유해야 효과적이다.',
     'bcrypt/scrypt/Argon2 는 키 스트레칭으로 brute-force 비용을 올린다.'],
    'SHA-256 을 한 번 돌리면 솔트 없이도 안전하다.',
    '고유 솔트 + bcrypt/Argon2/PBKDF2 키 스트레칭 해시 저장.',
    ['솔트를 소스 상수로 박으면 테이블별 공격이 불가능하다.',
     '사용자 ID 를 솔트로 재사용하면 관리가 편리하다.',
     'SHA-256 을 1,000 번 반복하면 충분한 스트레칭이다.']],
  ['IMP-SF-16','security_feature','java','반복된 인증시도 제한 기능 부재',
    ['무차별 대입은 IP/계정 양쪽 기준으로 제한해야 한다.',
     'Rate Limit + CAPTCHA + 점진적 지연 조합이 효과적이다.',
     '분산 공격 대응을 위해 Redis 등 전역 카운터가 필요하다.'],
    '로그인 실패를 무제한 허용해야 사용자 편의성이 유지된다.',
    'IP+계정 기반 Rate Limit + CAPTCHA + 점진적 지연.',
    ['반복 실패 시 계정을 영구 삭제하면 가장 안전하다.',
     'DB 락만 걸면 분산 환경에서도 차단 가능하다.',
     '로그만 남기고 제한은 걸지 않는다.']],
  ['IMP-TS-01','time_state','etc','경쟁조건: 검사시점과 사용시점',
    ['access() 검사 후 open() 사용 사이에 파일이 교체될 수 있다.',
     '심볼릭 링크 교체로 권한 경계를 우회할 수 있다.',
     'openat(O_NOFOLLOW) 로 심볼릭 링크 따라가기를 차단한다.'],
    'access(path) 후 곧바로 open(path) 를 호출하면 경쟁 조건이 발생하지 않는다.',
    'openat + fchown/fstat 같은 원자적 파일 디스크립터 연산.',
    ['read/write 함수에는 경쟁 조건이 없다.',
     'mutex 하나면 모든 파일 경쟁 조건을 해결한다.',
     '파일을 root 로 검사하고 일반 권한으로 쓰면 안전하다.']],
  ['IMP-TS-02','time_state','java','종료되지 않는 반복문 또는 재귀 함수',
    ['외부 입력이 반복 횟수를 결정하면 DoS 위험이 커진다.',
     '재귀 깊이 제한 없이 돌리면 스택 오버플로우가 난다.',
     '타임아웃·최대 반복·입력 상한 검증이 기본 방어다.'],
    'while(true) 구조는 내부 조건만 잘 두면 외부 입력의 영향이 없다.',
    '입력 범위 검증 + 최대 반복/깊이 상한 + 타임아웃.',
    ['자바는 꼬리 재귀 최적화가 있어 깊이 제한이 불필요하다.',
     'async 로 바꾸면 모든 무한 루프가 안전해진다.',
     'CPU 가 빠르면 무한 루프도 결국 끝난다.']],
  ['IMP-SF-11','security_feature','java','부적절한 인증서 유효성 검증',
    ['TLS 연결 시 인증서 체인, 유효 기간, 호스트명(CN/SAN) 모두 검증한다.',
     'trust-all TrustManager 는 MitM 에 무방비한 상태다.',
     'Pin(인증서 고정)은 CA 신뢰 체인 외의 추가 방어층이다.'],
    '자체 서명 인증서는 검증만 끄면 개발·운영 모두 문제가 없다.',
    '기본 TrustManager 사용 + 호스트명 검증 + 필요 시 pinning.',
    ['인증서가 유효한 기간 내면 호스트명이 다르더라도 접속한다.',
     'TrustManagerFactory 를 null 로 주면 검증이 자동된다.',
     'OCSP 확인은 속도가 느려 비활성화가 권장된다.']],
];

// 해설 템플릿 — 각 챕터의 취약점 핵심 원리를 간결히 요약
const EXPL_MAP = {};
try {
  Object.assign(EXPL_MAP, require('./kisa-explanations'));
} catch (_) {}

// REBUILD16 R4: shuffleKeep 은 scripts/seed/_utils.js 에서 import (위 require)

function buildQ1(row) {
  // "옳지 않은 것" — 선택지 4개 중 1개(concept_wrong)가 정답
  const [code, cat, lang, name, conceptOk, conceptWrong] = row;
  const options = [...conceptOk, conceptWrong];  // correct index = 3
  const { arr, newCorrect } = shuffleKeep(options, 3);
  return {
    question_type: 'mcq',
    weakness_category: cat,
    weakness_code: `${code}-MCQ-X-A`,
    chapter_code: code,
    weakness_name_ko: name,
    language: lang,
    difficulty: '중',
    body: `${name}에 대한 설명 중 옳지 **않은** 것을 고르시오.`,
    choices: arr.map((t, i) => ({ num: i + 1, text: t })),
    answer_index: newCorrect,
    model_answer: {
      correct_choice: newCorrect + 1,
      rationale: EXPL_MAP[code] || `${name} 취약점의 본질과 방어 원리 숙지가 필요합니다.`,
    },
    explanation: `정답: ${newCorrect + 1}번\n\n해설:\n${EXPL_MAP[code] || `${name} 의 취약점 원리 문항입니다.`}\n\n오답(정답 외)은 실제로 맞는 설명입니다.`,
    reference: `진단가이드 §${name}`,
    tags: ['mcq', 'implementation', 'auto-seed', 'pool-expand'],
    is_active: true,
  };
}

function buildQ2(row) {
  // "방어 방법 중 옳은 것" — defense_correct 가 정답, defense_wrong 3개가 오답
  const [code, cat, lang, name, , , defenseOk, defenseWrong] = row;
  const options = [defenseOk, ...defenseWrong];  // correct index = 0
  const { arr, newCorrect } = shuffleKeep(options, 0);
  return {
    question_type: 'mcq',
    weakness_category: cat,
    weakness_code: `${code}-MCQ-X-B`,
    chapter_code: code,
    weakness_name_ko: name,
    language: lang,
    difficulty: '중',
    body: `${name} 에 대한 방어 방법 중 **옳은** 것을 고르시오.`,
    choices: arr.map((t, i) => ({ num: i + 1, text: t })),
    answer_index: newCorrect,
    model_answer: {
      correct_choice: newCorrect + 1,
      rationale: EXPL_MAP[code] || `${name} 의 표준 방어 기법 숙지가 필요합니다.`,
    },
    explanation: `정답: ${newCorrect + 1}번\n\n해설:\n${EXPL_MAP[code] || `${name} 의 올바른 방어 기법을 묻는 문항입니다.`}\n\n오답은 실무에서 흔한 오해이거나 부분적 해결에 불과합니다.`,
    reference: `진단가이드 §${name}`,
    tags: ['mcq', 'implementation', 'auto-seed', 'pool-expand'],
    is_active: true,
  };
}

// 시드 고정 (테스트 재현용) — Math.random 을 결정론적으로 하진 않지만 매 실행 유사 분포
const questions = [];
for (const row of TOPICS) {
  questions.push(buildQ1(row));
  questions.push(buildQ2(row));
}

const outPath = writeSeedJson('kisa-module/seed/mcq-extra-questions.json', { questions });
console.log(`✅ 생성 완료: ${questions.length}문제 → ${outPath}`);
console.log(`   chapters: ${TOPICS.length} × 2 MCQ`);
