#!/usr/bin/env node
/**
 * KISA 단답형(blank) 문제 seed 생성기 (69챕터 × 2문제 = 138문제)
 * REBUILD16 §10 Stage 3 (R4) — scripts/seed/ 표준 위치로 이전, 공통 헬퍼 사용.
 *
 * 각 챕터의 핵심 방어 기술·API·개념을 기반으로 두 가지 관점의 단답형 문제를 생성한다:
 *   Q1 (개념/용어): 취약점의 원리와 핵심 기법
 *   Q2 (구현/API):  언어·프레임워크별 방어 API
 *
 * 출력: kisa-module/seed/blank-questions.json ({questions:[...]})
 *
 * 사용법:
 *   node scripts/seed/kisa-blank.js
 *
 * 결과 파일을 Admin 시드 엔드포인트(/api/kisa-admin?action=seed)로 업로드하면
 * kisa_questions 테이블에 blank 타입으로 등록된다.
 */
const EXPLANATIONS = require('./kisa-explanations');
const { writeSeedJson } = require('./_utils');

// 각 챕터별 문제 2개 — 핵심 방어 개념/API 기반
// 형식: [chapter_code, weakness_name_ko, language, category, stage, Q1{template, answers}, Q2{template, answers}, difficulty]
const TOPICS = [
  // ================== Design 20개 ==================
  ['DSG-IV-01','DBMS 조회 및 결과 검증','java','input_validation','design',
    { tmpl:'DBMS 조회 시 SQL 삽입을 막기 위해 Java에서는 JDBC의 {{1}}를 사용하여 ? 바인드 파라미터로 쿼리와 데이터를 분리한다.',
      ans:[{idx:1,answers:['PreparedStatement'],synonyms:['preparedstatement']}] },
    { tmpl:'MyBatis 프레임워크에서는 문자열 치환 {{1}} 대신 바인드 파라미터 {{2}} 문법을 사용해야 SQL 삽입을 방지할 수 있다.',
      ans:[{idx:1,answers:['${}'],synonyms:['${','달러중괄호']},{idx:2,answers:['#{}'],synonyms:['#{','샵중괄호']}] },
    '중'],
  ['DSG-IV-02','XML 조회 및 결과 검증','java','input_validation','design',
    { tmpl:'XPath/XQuery 질의에서 사용자 입력을 문자열로 결합하면 {{1}} 취약점이 발생하므로 매개변수 바인딩을 사용해야 한다.',
      ans:[{idx:1,answers:['XPath Injection','XPath 삽입'],synonyms:['xpath injection','xpath 주입']}] },
    { tmpl:'Java에서 안전한 XPath 질의를 위해 javax.xml.xpath의 XPathExpression과 {{1}} 기반 변수 바인딩을 사용한다.',
      ans:[{idx:1,answers:['XPathVariableResolver'],synonyms:['xpath variable resolver']}] },
    '중'],
  ['DSG-IV-03','디렉토리 서비스 조회 및 결과 검증','java','input_validation','design',
    { tmpl:'LDAP 질의 시 사용자 입력을 그대로 삽입하면 {{1}} 취약점이 발생한다. 특수문자 *, (, ), \\ 등을 이스케이프해야 한다.',
      ans:[{idx:1,answers:['LDAP Injection','LDAP 삽입'],synonyms:['ldap injection','ldap 주입']}] },
    { tmpl:'Spring LDAP 에서는 {{1}} 클래스를 사용해 입력값을 안전하게 필터 구성해야 한다.',
      ans:[{idx:1,answers:['LdapEncoder','Filter.encode'],synonyms:['ldap encoder']}] },
    '상'],
  ['DSG-IV-04','시스템 자원 접근 및 명령어 수행 입력값 검증','java','input_validation','design',
    { tmpl:'Runtime.exec 나 ProcessBuilder 호출 시 외부 입력을 문자열로 연결하면 {{1}} 공격이 가능하다.',
      ans:[{idx:1,answers:['OS Command Injection','운영체제 명령어 삽입'],synonyms:['command injection','명령어 주입']}] },
    { tmpl:'안전한 명령 실행을 위해서는 {{1}}에 인자를 배열로 전달하고 셸 메타문자를 화이트리스트로 검증한다.',
      ans:[{idx:1,answers:['ProcessBuilder'],synonyms:['process builder']}] },
    '중'],
  ['DSG-IV-05','웹 서비스 요청 및 결과 검증','java','input_validation','design',
    { tmpl:'서버가 외부 URL을 사용자 입력 그대로 호출할 경우 내부망 스캔 등 {{1}} 취약점이 발생한다.',
      ans:[{idx:1,answers:['SSRF','서버사이드 요청 위조'],synonyms:['server-side request forgery']}] },
    { tmpl:'SSRF 방어를 위해 외부 요청 대상을 {{1}} 기반으로 제한하고, 메타데이터 서비스(169.254.169.254) 접근을 차단한다.',
      ans:[{idx:1,answers:['allowlist','화이트리스트'],synonyms:['allow list','whitelist']}] },
    '상'],
  ['DSG-IV-06','웹 기반 중요기능 수행 요청 유효성 검증','java','input_validation','design',
    { tmpl:'세션만으로 중요기능을 승인하면 외부 사이트의 자동 POST에 의해 {{1}} 공격에 노출된다.',
      ans:[{idx:1,answers:['CSRF','크로스사이트 요청 위조'],synonyms:['cross-site request forgery']}] },
    { tmpl:'Spring Security는 기본적으로 {{1}} 필터로 토큰을 검증하며, 쿠키에는 {{2}}=Strict 속성을 함께 적용하면 효과적이다.',
      ans:[{idx:1,answers:['CsrfFilter'],synonyms:['csrf filter']},{idx:2,answers:['SameSite'],synonyms:['same-site']}] },
    '중'],
  ['DSG-IV-07','HTTP 프로토콜 유효성 검증','java','input_validation','design',
    { tmpl:'HTTP 응답 헤더에 사용자 입력이 그대로 삽입되면 {{1}} 공격이 발생한다. 개행문자 CR/LF를 제거해야 한다.',
      ans:[{idx:1,answers:['HTTP Response Splitting','HTTP 응답분할'],synonyms:['http response splitting']}] },
    { tmpl:'응답 헤더에 데이터를 실을 때는 {{1}} 유틸로 CR(0x0D)/LF(0x0A) 문자를 제거하거나 거부한다.',
      ans:[{idx:1,answers:['encodeForHTTP','escapeHtml'],synonyms:['encode for http']}] },
    '중'],
  ['DSG-IV-08','허용된 범위내 메모리 접근','c','input_validation','design',
    { tmpl:'배열 인덱스가 허용 범위를 벗어나면 {{1}} 취약점이 발생하여 인접 메모리를 덮어쓸 수 있다.',
      ans:[{idx:1,answers:['Buffer Overflow','버퍼 오버플로우'],synonyms:['buffer overrun']}] },
    { tmpl:'C/C++에서는 strcpy 대신 {{1}}처럼 크기 제한 함수를 사용하고 인덱스를 검증해야 한다.',
      ans:[{idx:1,answers:['strncpy','strlcpy'],synonyms:['strn cpy']}] },
    '상'],
  ['DSG-IV-09','보안기능 입력값 검증','java','input_validation','design',
    { tmpl:'인증·인가 결정에 사용되는 입력은 반드시 {{1}} 방식으로 검증해야 한다 (허용 목록만 통과).',
      ans:[{idx:1,answers:['화이트리스트','allowlist'],synonyms:['allow list','whitelist']}] },
    { tmpl:'서버 측 검증을 우회 당하지 않으려면 {{1}} 검증만 신뢰해서는 안 되며 반드시 서버 측에서 재검증한다.',
      ans:[{idx:1,answers:['클라이언트','client'],synonyms:['client-side','클라이언트측']}] },
    '하'],
  ['DSG-IV-10','업로드·다운로드 파일 검증','java','input_validation','design',
    { tmpl:'파일 다운로드 경로에 사용자 입력(../)이 포함되면 {{1}} 공격으로 임의 파일 접근이 가능하다.',
      ans:[{idx:1,answers:['Path Traversal','경로 조작'],synonyms:['directory traversal']}] },
    { tmpl:'업로드 파일은 {{1}} 검사로 실제 콘텐츠 타입을 확인하고 실행 가능한 확장자는 저장 전 거부한다.',
      ans:[{idx:1,answers:['Magic Number','MIME','매직넘버'],synonyms:['magic bytes','파일 시그니처']}] },
    '중'],
  ['DSG-SF-01','인증대상 및 방식','java','security_feature','design',
    { tmpl:'인증수단을 한 가지 요소만 사용하면 보안이 약해지므로 {{1}} (MFA)를 적용해야 한다.',
      ans:[{idx:1,answers:['다중 인증','Multi-Factor Authentication'],synonyms:['mfa','multi factor','2fa']}] },
    { tmpl:'OTP, 생체정보는 {{1}} 인증의 예시이며, 서버 저장 시에는 해시·암호화된 상태로 보관한다.',
      ans:[{idx:1,answers:['2차','second factor'],synonyms:['2단계','추가']}] },
    '중'],
  ['DSG-SF-02','인증수행 제한','java','security_feature','design',
    { tmpl:'로그인 실패 횟수에 제한이 없으면 {{1}} 공격에 취약해진다.',
      ans:[{idx:1,answers:['Brute Force','무차별 대입'],synonyms:['brute-force','브루트포스']}] },
    { tmpl:'IP·계정 기준 연속 실패 N회 시 임시 잠금이나 {{1}} 제시 등 진행 제한이 필요하다.',
      ans:[{idx:1,answers:['CAPTCHA'],synonyms:['캡차','캡챠']}] },
    '하'],
  ['DSG-SF-03','비밀번호 관리','java','security_feature','design',
    { tmpl:'비밀번호는 평문 저장이 아니라 솔트와 함께 {{1}} 해시로 저장해야 한다 (bcrypt, scrypt, Argon2 등).',
      ans:[{idx:1,answers:['단방향','one-way'],synonyms:['일방향']}] },
    { tmpl:'비밀번호 정책은 길이 {{1}}자 이상, 대소문자·숫자·특수문자 조합, 사전공격 단어 금지를 권고한다.',
      ans:[{idx:1,answers:['8','10','12'],synonyms:['여덟','8자']}] },
    '하'],
  ['DSG-SF-04','중요자원 접근통제','java','security_feature','design',
    { tmpl:'접근통제는 클라이언트가 아닌 {{1}} 측에서 수행해야 하며 매 요청마다 권한을 재확인해야 한다.',
      ans:[{idx:1,answers:['서버','server'],synonyms:['server-side','서버측']}] },
    { tmpl:'URL·파라미터로 자원 식별자를 직접 노출하면 권한 변경 없이 접근되는 {{1}} 취약점이 발생한다.',
      ans:[{idx:1,answers:['IDOR','Insecure Direct Object Reference'],synonyms:['insecure direct object reference','불안전한 직접 객체 참조']}] },
    '중'],
  ['DSG-SF-05','암호키 관리','java','security_feature','design',
    { tmpl:'암호키를 소스코드에 하드코딩하면 {{1}} 취약점이 된다. 키는 별도 KMS 또는 Secret Manager에 보관해야 한다.',
      ans:[{idx:1,answers:['Hardcoded Credentials','하드코드된 중요정보'],synonyms:['hardcoded secret','하드코딩']}] },
    { tmpl:'대칭키는 최소 {{1}} bit AES, 비대칭키는 최소 2048bit RSA 또는 256bit ECC를 사용한다.',
      ans:[{idx:1,answers:['128','256'],synonyms:['128bit','128비트']}] },
    '중'],
  ['DSG-SF-06','암호연산','java','security_feature','design',
    { tmpl:'DES, MD5, SHA-1은 {{1}} 알고리즘으로 분류되어 사용을 금지한다.',
      ans:[{idx:1,answers:['취약한','deprecated'],synonyms:['약한','weak','폐기된']}] },
    { tmpl:'블록 암호 모드는 ECB 대신 {{1}}나 GCM 같은 인증 암호화 모드를 사용해야 한다.',
      ans:[{idx:1,answers:['CBC','CTR','GCM'],synonyms:['cipher block chaining']}] },
    '중'],
  ['DSG-SF-07','중요정보 저장','java','security_feature','design',
    { tmpl:'개인정보·금융정보는 저장 시 반드시 {{1}}되어야 하며, 복호화 키는 데이터와 분리 보관한다.',
      ans:[{idx:1,answers:['암호화','encrypt'],synonyms:['encryption','암호화저장']}] },
    { tmpl:'비밀번호는 solt(소금값)과 함께 {{1}} 같은 키 스트레칭 해시로 저장한다.',
      ans:[{idx:1,answers:['bcrypt','scrypt','Argon2','PBKDF2'],synonyms:['b crypt','pbkdf 2']}] },
    '중'],
  ['DSG-SF-08','중요정보 전송','java','security_feature','design',
    { tmpl:'중요 정보 전송 시 반드시 {{1}} (HTTPS) 사용해 도청을 방지해야 한다.',
      ans:[{idx:1,answers:['TLS','SSL'],synonyms:['transport layer security']}] },
    { tmpl:'민감 파라미터는 URL 쿼리 스트링이 아니라 요청 {{1}}에 실어 전송해야 로그/Referer 노출을 피할 수 있다.',
      ans:[{idx:1,answers:['body','바디'],synonyms:['본문','request body']}] },
    '하'],
  ['DSG-EH-01','예외처리 설계','java','error_handling','design',
    { tmpl:'예외 메시지에 {{1}}(스택트레이스)를 그대로 노출하면 시스템 구조와 취약점 정보가 유출된다.',
      ans:[{idx:1,answers:['stack trace','스택트레이스'],synonyms:['stacktrace','호출스택']}] },
    { tmpl:'사용자에게는 일반화된 오류 메시지를 보여주고 상세 오류는 {{1}}에만 기록해야 한다.',
      ans:[{idx:1,answers:['log','로그'],synonyms:['logfile','서버 로그']}] },
    '하'],
  ['DSG-SC-01','세션통제 설계','java','session_control','design',
    { tmpl:'로그인 성공 후에는 반드시 {{1}} 재발급을 수행하여 세션 고정(Session Fixation) 공격을 방지한다.',
      ans:[{idx:1,answers:['세션 ID','session id'],synonyms:['sessionid','session token']}] },
    { tmpl:'세션 쿠키에는 {{1}}, HttpOnly, Secure 속성을 함께 설정한다.',
      ans:[{idx:1,answers:['SameSite'],synonyms:['same-site']}] },
    '중'],

  // ================== Implementation-1 17개 ==================
  ['IMP-IV-01','SQL 삽입','java','input_validation','implementation',
    { tmpl:'Java에서 SQL 삽입을 방어하는 표준 API는 {{1}}이며 ? 바인드 파라미터로 쿼리와 데이터를 분리한다.',
      ans:[{idx:1,answers:['PreparedStatement'],synonyms:['prepared statement']}] },
    { tmpl:'MyBatis에서 바인드 파라미터는 {{1}} 문법을 사용하고 문자열 치환 ${} 사용은 피한다.',
      ans:[{idx:1,answers:['#{}','#{'],synonyms:['샵중괄호']}] },
    '하'],
  ['IMP-IV-02','코드 삽입','javascript','input_validation','implementation',
    { tmpl:'eval() 함수에 사용자 입력을 그대로 넘기면 {{1}} 취약점이 되며, 필요 시 JSON.parse 등 안전한 대안을 사용한다.',
      ans:[{idx:1,answers:['Code Injection','코드 삽입'],synonyms:['code injection']}] },
    { tmpl:'서버 사이드 템플릿에서 {{1}} 로 표시되는 영역에 사용자 입력을 그대로 넣으면 SSTI 취약점이 된다.',
      ans:[{idx:1,answers:['{{ }}','#{','${'],synonyms:['이중중괄호']}] },
    '중'],
  ['IMP-IV-03','경로 조작 및 자원 삽입','java','input_validation','implementation',
    { tmpl:'파일 경로에 ".."가 포함되면 상위 디렉토리 접근이 가능한 {{1}} 취약점이 발생한다.',
      ans:[{idx:1,answers:['Path Traversal','경로 조작'],synonyms:['directory traversal']}] },
    { tmpl:'Java 에서는 File.{{1}}() 로 정규화 후 허용 루트로 시작하는지 startsWith 검사로 확인해야 한다.',
      ans:[{idx:1,answers:['getCanonicalPath','toRealPath'],synonyms:['canonical path']}] },
    '중'],
  ['IMP-IV-04','크로스사이트 스크립트','java','input_validation','implementation',
    { tmpl:'HTML 출력 시 사용자 입력을 이스케이프하지 않으면 {{1}} 공격이 발생한다.',
      ans:[{idx:1,answers:['XSS','Cross-Site Scripting'],synonyms:['xss','크로스사이트 스크립팅']}] },
    { tmpl:'Java/Spring에서는 출력 시 {{1}} 유틸로 <, >, ", \' & 를 이스케이프한다.',
      ans:[{idx:1,answers:['HtmlUtils.htmlEscape','StringEscapeUtils.escapeHtml4'],synonyms:['escape html']}] },
    '하'],
  ['IMP-IV-05','운영체제 명령어 삽입','java','input_validation','implementation',
    { tmpl:'Runtime.getRuntime().exec 에 사용자 입력을 연결하면 {{1}} 공격이 가능하다.',
      ans:[{idx:1,answers:['OS Command Injection','명령어 삽입'],synonyms:['command injection']}] },
    { tmpl:'명령 실행은 {{1}}에 인자를 배열로 전달하고 셸 해석을 피한다.',
      ans:[{idx:1,answers:['ProcessBuilder'],synonyms:['process builder']}] },
    '중'],
  ['IMP-IV-06','위험한 형식 파일 업로드','java','input_validation','implementation',
    { tmpl:'업로드된 파일을 실행 가능한 경로에 저장하고 {{1}} 확장자를 허용하면 웹쉘이 업로드될 수 있다.',
      ans:[{idx:1,answers:['.jsp','.php','.exe'],synonyms:['jsp','php','exe']}] },
    { tmpl:'서버는 {{1}} 매직 바이트로 실제 타입을 확인하고 업로드 디렉토리에서 실행권한을 제거해야 한다.',
      ans:[{idx:1,answers:['Magic Number','매직넘버','파일 시그니처'],synonyms:['magic bytes']}] },
    '중'],
  ['IMP-IV-07','신뢰되지 않는 URL 주소로 자동접속 연결','java','input_validation','implementation',
    { tmpl:'로그인 후 redirect URL 파라미터를 그대로 사용하면 {{1}} 취약점이 발생한다.',
      ans:[{idx:1,answers:['Open Redirect','오픈 리다이렉트'],synonyms:['open redirection']}] },
    { tmpl:'안전한 리다이렉트를 위해 목적지 URL을 {{1}} 기준으로 제한하고 외부 호스트 이동은 경고한다.',
      ans:[{idx:1,answers:['allowlist','화이트리스트'],synonyms:['허용목록']}] },
    '하'],
  ['IMP-IV-08','부적절한 XML 외부 개체 참조','java','input_validation','implementation',
    { tmpl:'XML 파서가 외부 엔티티를 해석하면 {{1}} 취약점으로 로컬 파일 유출 또는 SSRF가 발생한다.',
      ans:[{idx:1,answers:['XXE','XML External Entity'],synonyms:['xxe','외부 엔티티']}] },
    { tmpl:'Java 에서는 DocumentBuilderFactory에 FEATURE {{1}}=false 를 설정해 DTD 처리를 비활성화한다.',
      ans:[{idx:1,answers:['disallow-doctype-decl','load-external-dtd','external-parameter-entities'],synonyms:['dtd']}] },
    '상'],
  ['IMP-IV-09','XML 삽입','java','input_validation','implementation',
    { tmpl:'XML 구조에 사용자 입력이 그대로 삽입되면 구조가 왜곡되어 {{1}} 취약점이 발생한다.',
      ans:[{idx:1,answers:['XML Injection','XML 삽입'],synonyms:['xml injection']}] },
    { tmpl:'XML 구성 시에는 DOM API로 요소·속성을 생성하거나 메타문자 {{1}}, {{2}}를 이스케이프한다.',
      ans:[{idx:1,answers:['<'],synonyms:['less than']},{idx:2,answers:['>'],synonyms:['greater than']}] },
    '상'],
  ['IMP-IV-10','LDAP 삽입','java','input_validation','implementation',
    { tmpl:'LDAP 필터에 사용자 입력이 직접 삽입되면 {{1}} 취약점이 발생한다.',
      ans:[{idx:1,answers:['LDAP Injection','LDAP 삽입'],synonyms:['ldap injection']}] },
    { tmpl:'LDAP 필터의 특수문자 *, (, ), \\, NUL 을 {{1}} 형식으로 이스케이프해야 한다.',
      ans:[{idx:1,answers:['\\xx','백슬래시 헥스'],synonyms:['backslash hex','hex escape']}] },
    '상'],
  ['IMP-IV-11','크로스사이트 요청 위조','java','input_validation','implementation',
    { tmpl:'세션만으로 중요 요청을 허용하면 외부 사이트에서 자동 POST를 유도하는 {{1}} 공격이 가능하다.',
      ans:[{idx:1,answers:['CSRF','크로스사이트 요청 위조'],synonyms:['cross-site request forgery']}] },
    { tmpl:'Spring Security는 {{1}} 패턴의 토큰을 요청마다 검증하며, 쿠키에 SameSite 속성을 함께 권장한다.',
      ans:[{idx:1,answers:['Synchronizer Token','CSRF Token'],synonyms:['동기화 토큰','csrf 토큰']}] },
    '하'],
  ['IMP-IV-12','서버사이드 요청 위조','java','input_validation','implementation',
    { tmpl:'서버가 사용자 입력 URL을 그대로 호출해 내부망·메타데이터 서비스에 접근하는 취약점은 {{1}}이다.',
      ans:[{idx:1,answers:['SSRF','서버사이드 요청 위조'],synonyms:['server-side request forgery']}] },
    { tmpl:'SSRF 방어 시 클라우드 메타데이터 IP {{1}}로의 접근을 차단해야 한다.',
      ans:[{idx:1,answers:['169.254.169.254'],synonyms:['169.254']}] },
    '상'],
  ['IMP-IV-13','HTTP 응답분할','java','input_validation','implementation',
    { tmpl:'응답 헤더에 개행문자 {{1}}/{{2}}를 포함한 입력을 그대로 넣으면 HTTP 응답분할 공격이 발생한다.',
      ans:[{idx:1,answers:['CR','\\r','0x0D'],synonyms:['carriage return']},{idx:2,answers:['LF','\\n','0x0A'],synonyms:['line feed']}] },
    { tmpl:'응답 헤더 작성 전에는 개행·공백·탭 문자를 {{1}}(제거 또는 거부)해야 한다.',
      ans:[{idx:1,answers:['필터링','sanitize'],synonyms:['새니타이징','필터']}] },
    '중'],
  ['IMP-IV-14','정수형 오버플로우','c','input_validation','implementation',
    { tmpl:'유효 범위를 초과한 정수 연산은 {{1}} 현상을 일으켜 인덱스 계산·길이 검증을 우회할 수 있다.',
      ans:[{idx:1,answers:['Integer Overflow','정수 오버플로우'],synonyms:['wraparound','wrap-around']}] },
    { tmpl:'C에서는 size_t 곱셈 전에 {{1}} 함수로 overflow 체크 후 할당해야 한다.',
      ans:[{idx:1,answers:['__builtin_mul_overflow','ckd_mul'],synonyms:['builtin mul overflow']}] },
    '상'],
  ['IMP-IV-15','보안기능 결정에 사용되는 부적절한 입력값','java','input_validation','implementation',
    { tmpl:'권한·인증 판단을 {{1}} 입력값에만 의존하면 우회가 가능하므로 서버 측에서 재검증해야 한다.',
      ans:[{idx:1,answers:['client','클라이언트'],synonyms:['client-side','hidden']}] },
    { tmpl:'세션이 아닌 {{1}} 값으로 권한을 결정하면 변조 위험이 크다.',
      ans:[{idx:1,answers:['cookie','쿠키'],synonyms:['쿠키값']}] },
    '중'],
  ['IMP-IV-16','메모리 버퍼 오버플로우','c','input_validation','implementation',
    { tmpl:'strcpy, sprintf 같은 {{1}} 검사 없는 함수는 버퍼 오버플로우의 주요 원인이다.',
      ans:[{idx:1,answers:['길이','bounds'],synonyms:['length','경계']}] },
    { tmpl:'이들을 대체해 strcpy는 {{1}}, sprintf는 snprintf 등 크기 제한 함수를 사용한다.',
      ans:[{idx:1,answers:['strncpy','strlcpy'],synonyms:['str n cpy']}] },
    '상'],
  ['IMP-IV-17','포맷 스트링 삽입','c','input_validation','implementation',
    { tmpl:'printf(userInput) 처럼 사용자 입력을 포맷 문자열로 쓰면 {{1}} 취약점으로 메모리 노출이 발생한다.',
      ans:[{idx:1,answers:['Format String','포맷 스트링'],synonyms:['format string injection']}] },
    { tmpl:'올바른 사용법은 printf("{{1}}", userInput) 처럼 고정 포맷 문자열을 사용하는 것이다.',
      ans:[{idx:1,answers:['%s'],synonyms:['percent s','문자열 포맷']}] },
    '상'],

  // ================== Implementation-2 (나머지 32개) ==================
  ['IMP-SF-01','적절한 인증 없는 중요기능 허용','java','security_feature','implementation',
    { tmpl:'인증 없이 접근 가능한 중요 기능은 {{1}} 검증을 서버 측에서 반드시 수행해야 한다.',
      ans:[{idx:1,answers:['인증','authentication'],synonyms:['auth','인증여부']}] },
    { tmpl:'Spring Security 에서는 {{1}} 애노테이션으로 메소드 수준 인가 검사를 적용할 수 있다.',
      ans:[{idx:1,answers:['@PreAuthorize'],synonyms:['pre authorize','preauthorize']}] },
    '하'],
  ['IMP-SF-02','부적절한 인가','java','security_feature','implementation',
    { tmpl:'역할은 있으나 리소스 단위 검증을 빠뜨리면 {{1}} 취약점이 발생한다.',
      ans:[{idx:1,answers:['IDOR','Broken Authorization'],synonyms:['insecure direct object reference','부적절한 인가']}] },
    { tmpl:'요청마다 자원 소유자와 현재 사용자 {{1}}를 비교해 인가를 수행한다.',
      ans:[{idx:1,answers:['ID','식별자'],synonyms:['user id','uid']}] },
    '중'],
  ['IMP-SF-03','중요한 자원에 대한 잘못된 권한 설정','java','security_feature','implementation',
    { tmpl:'중요 파일·디렉토리는 최소 권한 원칙에 따라 chmod {{1}} 정도로 접근 권한을 제한한다.',
      ans:[{idx:1,answers:['600','640','700'],synonyms:['rw-','rwx']}] },
    { tmpl:'리눅스에서는 {{1}} 명령으로 소유자·그룹·기타의 권한을 분리 지정한다.',
      ans:[{idx:1,answers:['chmod'],synonyms:['change mode']}] },
    '하'],
  ['IMP-SF-04','취약한 암호화 알고리즘 사용','java','security_feature','implementation',
    { tmpl:'DES, 3DES, {{1}}, RC4 등은 금지 대상 알고리즘으로 AES-256 또는 ChaCha20으로 대체해야 한다.',
      ans:[{idx:1,answers:['MD5','SHA-1'],synonyms:['sha1','md 5']}] },
    { tmpl:'Java Cipher는 안전한 모드인 AES/{{1}}/NoPadding 또는 AES/GCM 을 사용한다.',
      ans:[{idx:1,answers:['CBC','CTR','GCM'],synonyms:['cipher block chaining']}] },
    '중'],
  ['IMP-SF-05','암호화되지 않은 중요정보','java','security_feature','implementation',
    { tmpl:'저장 시 중요정보는 {{1}} 되지 않으면 DB 유출 시 그대로 노출된다.',
      ans:[{idx:1,answers:['암호화','encrypt'],synonyms:['encryption']}] },
    { tmpl:'전송 구간은 {{1}} (HTTPS) 적용이 필수다.',
      ans:[{idx:1,answers:['TLS','SSL'],synonyms:['https']}] },
    '하'],
  ['IMP-SF-06','하드코드된 중요정보','java','security_feature','implementation',
    { tmpl:'API 키·비밀번호를 소스에 박아두면 {{1}} 취약점이 된다.',
      ans:[{idx:1,answers:['Hardcoded Credentials','하드코드된 중요정보'],synonyms:['hardcoded secret']}] },
    { tmpl:'이들은 환경변수, {{1}} (AWS Secrets Manager/GCP Secret Manager 등)로 이관해야 한다.',
      ans:[{idx:1,answers:['Secret Manager','KMS'],synonyms:['secretmanager','key management service']}] },
    '하'],
  ['IMP-SF-07','충분하지 않은 키 길이 사용','java','security_feature','implementation',
    { tmpl:'RSA 키는 최소 {{1}} bit, ECC는 256bit, AES 대칭키는 128bit 이상을 사용한다.',
      ans:[{idx:1,answers:['2048'],synonyms:['2048 bit']}] },
    { tmpl:'HMAC SHA-256 등의 경우 키 길이는 최소 출력 길이와 같은 {{1}} bit 이상이 권장된다.',
      ans:[{idx:1,answers:['256'],synonyms:['256 bit']}] },
    '중'],
  ['IMP-SF-08','적절하지 않은 난수값 사용','java','security_feature','implementation',
    { tmpl:'보안 용도로는 java.util.Random 대신 {{1}} 클래스를 사용해야 예측 불가능한 난수를 얻는다.',
      ans:[{idx:1,answers:['SecureRandom'],synonyms:['secure random']}] },
    { tmpl:'시드로 {{1}}를 사용하면 재현 가능해 보안에 부적합하다.',
      ans:[{idx:1,answers:['System.currentTimeMillis','current time','타임스탬프'],synonyms:['현재 시간']}] },
    '중'],
  ['IMP-SF-09','취약한 비밀번호 허용','java','security_feature','implementation',
    { tmpl:'비밀번호 정책은 길이 {{1}}자 이상, 사전 단어·연속 문자 금지 등을 서버에서 검증해야 한다.',
      ans:[{idx:1,answers:['8','10','12'],synonyms:['eight','여덟']}] },
    { tmpl:'자주 쓰이는 비밀번호는 {{1}} 목록(HaveIBeenPwned 등)과 대조해 거부한다.',
      ans:[{idx:1,answers:['blocklist','deny list','유출'],synonyms:['blacklist','유출 목록']}] },
    '하'],
  ['IMP-SF-10','부적절한 전자서명 확인','java','security_feature','implementation',
    { tmpl:'서명 검증을 생략하거나 {{1}} 알고리즘으로 구현하면 위조 메시지를 수용할 수 있다.',
      ans:[{idx:1,answers:['none','None'],synonyms:['널 알고리즘','noop']}] },
    { tmpl:'JWT 검증 시 헤더의 alg 필드를 신뢰하지 말고 서버 정책으로 {{1}} 알고리즘만 허용한다.',
      ans:[{idx:1,answers:['RS256','ES256','HS256'],synonyms:['rsa256','ecdsa256']}] },
    '상'],
  ['IMP-SF-11','부적절한 인증서 유효성 검증','java','security_feature','implementation',
    { tmpl:'TLS 연결 시 인증서 {{1}}과 유효기간·CN/SAN을 반드시 검증해야 한다.',
      ans:[{idx:1,answers:['체인','chain'],synonyms:['trust chain','신뢰 체인']}] },
    { tmpl:'인증서 검증을 비활성화한 TrustManager({{1}}=true) 같은 코드는 제거해야 한다.',
      ans:[{idx:1,answers:['trustAll','trust-all'],synonyms:['trust all','항상 신뢰']}] },
    '상'],
  ['IMP-SF-12','사용자 하드디스크에 저장되는 쿠키를 통한 정보 노출','java','security_feature','implementation',
    { tmpl:'민감정보를 {{1}} 쿠키로 저장하면 브라우저 종료 후에도 파일로 남아 노출 위험이 있다.',
      ans:[{idx:1,answers:['persistent','영구'],synonyms:['persistent cookie','영구 쿠키']}] },
    { tmpl:'세션쿠키는 {{1}} 속성 없이 발급해 브라우저 종료 시 삭제되게 하고 HttpOnly·Secure를 함께 적용한다.',
      ans:[{idx:1,answers:['Expires','Max-Age'],synonyms:['max age','만료']}] },
    '중'],
  ['IMP-SF-13','주석문 안에 포함된 시스템 주요정보','java','security_feature','implementation',
    { tmpl:'배포 코드의 주석에 남긴 {{1}}, API키, 내부 URL 등은 난독화되어도 추출 가능하므로 제거한다.',
      ans:[{idx:1,answers:['비밀번호','password'],synonyms:['credentials','계정']}] },
    { tmpl:'클라이언트 번들(JS)에서는 {{1}} 과정을 거쳐 주석을 제거해야 한다.',
      ans:[{idx:1,answers:['minify','minification'],synonyms:['minimize','압축']}] },
    '하'],
  ['IMP-SF-14','솔트 없이 일방향 해시함수 사용','java','security_feature','implementation',
    { tmpl:'솔트 없이 MD5/SHA-1 단일 해시를 사용하면 {{1}} 테이블로 역추적 가능하다.',
      ans:[{idx:1,answers:['Rainbow','레인보우'],synonyms:['rainbow table']}] },
    { tmpl:'비밀번호 해시는 솔트와 함께 {{1}} 같은 느린 해시(key stretching)을 사용한다.',
      ans:[{idx:1,answers:['bcrypt','scrypt','Argon2','PBKDF2'],synonyms:['b crypt']}] },
    '중'],
  ['IMP-SF-15','무결성 검사없는 코드 다운로드','java','security_feature','implementation',
    { tmpl:'외부에서 내려받은 코드는 {{1}} 검사(서명·해시 비교)로 무결성을 확인한 뒤 실행해야 한다.',
      ans:[{idx:1,answers:['해시','hash','서명'],synonyms:['signature','sha']}] },
    { tmpl:'npm·Maven에서는 lockfile 및 {{1}}로 의존성 무결성을 보장할 수 있다.',
      ans:[{idx:1,answers:['SRI','Subresource Integrity','checksum'],synonyms:['해시체크','sha-hash']}] },
    '상'],
  ['IMP-SF-16','반복된 인증시도 제한 기능 부재','java','security_feature','implementation',
    { tmpl:'실패 횟수 제한·지연·{{1}} 없이 로그인 API를 제공하면 무차별 대입에 취약하다.',
      ans:[{idx:1,answers:['CAPTCHA','캡차'],synonyms:['캡챠','reCAPTCHA']}] },
    { tmpl:'서버에서는 IP+계정별 {{1}} 알고리즘(Token Bucket/Leaky Bucket)으로 요청률을 제한한다.',
      ans:[{idx:1,answers:['Rate Limit','rate-limit','속도 제한'],synonyms:['rate limiting']}] },
    '중'],
  ['IMP-TS-01','경쟁조건: 검사시점과 사용시점','c','time_state','implementation',
    { tmpl:'access() 로 검사 후 open() 로 사용하는 사이에 파일이 바뀌면 {{1}} 취약점이 발생한다.',
      ans:[{idx:1,answers:['TOCTOU','Time-of-Check to Time-of-Use'],synonyms:['toctou','time of check']}] },
    { tmpl:'해결책으로는 {{1}} 시스템 콜을 사용해 파일 디스크립터 기반으로 원자적으로 작업한다.',
      ans:[{idx:1,answers:['openat','fchown','fstat'],synonyms:['open at']}] },
    '상'],
  ['IMP-TS-02','종료되지 않는 반복문 또는 재귀 함수','java','time_state','implementation',
    { tmpl:'외부 입력이 반복 횟수·재귀 깊이를 결정하면 {{1}} (서비스 거부)으로 이어질 수 있다.',
      ans:[{idx:1,answers:['DoS','Denial of Service'],synonyms:['서비스거부','denial-of-service']}] },
    { tmpl:'반복·재귀에는 입력 범위 검증과 {{1}} (최대 반복/깊이 제한)를 설정한다.',
      ans:[{idx:1,answers:['상한','bound','limit'],synonyms:['최대치','max']}] },
    '중'],
  ['IMP-EH-01','오류 메시지 정보노출','java','error_handling','implementation',
    { tmpl:'스택트레이스, SQL문, 내부 경로 등이 포함된 {{1}}는 공격자에게 힌트를 준다.',
      ans:[{idx:1,answers:['오류 메시지','error message'],synonyms:['에러 메시지','exception message']}] },
    { tmpl:'운영 환경에서는 상세 예외를 사용자에게 노출하지 말고 {{1}}에만 기록한다.',
      ans:[{idx:1,answers:['log','로그'],synonyms:['서버 로그','logfile']}] },
    '하'],
  ['IMP-EH-02','오류상황 대응 부재','java','error_handling','implementation',
    { tmpl:'예외를 {{1}} 블록 없이 그대로 전파하거나 무시하면 자원 유출이나 일관성 파괴가 생긴다.',
      ans:[{idx:1,answers:['try-catch','catch','예외'],synonyms:['try catch','try/catch']}] },
    { tmpl:'{{1}} 블록에서는 자원 해제를 수행하고 try-with-resources로 자동 해제 패턴을 권장한다.',
      ans:[{idx:1,answers:['finally'],synonyms:['파이널리']}] },
    '하'],
  ['IMP-EH-03','부적절한 예외 처리','java','error_handling','implementation',
    { tmpl:'catch 블록에서 예외를 {{1}} 처리하고 로그도 없으면 문제를 놓친다.',
      ans:[{idx:1,answers:['swallow','무시'],synonyms:['삼킴','empty catch']}] },
    { tmpl:'의미 있는 로그와 {{1}} (throw) 여부 판단이 필요하다.',
      ans:[{idx:1,answers:['재전파','rethrow'],synonyms:['re-throw','다시 던지기']}] },
    '하'],
  ['IMP-CE-01','Null Pointer 역참조','java','code_error','implementation',
    { tmpl:'객체가 null인 상태에서 {{1}} 연산을 수행하면 NullPointerException이 발생한다.',
      ans:[{idx:1,answers:['.','dot','메소드'],synonyms:['도트','메소드 호출']}] },
    { tmpl:'Java 에서는 {{1}}.ofNullable 과 ifPresent 로 안전하게 처리하거나 null 체크를 수행한다.',
      ans:[{idx:1,answers:['Optional'],synonyms:['옵셔널']}] },
    '하'],
  ['IMP-CE-02','부적절한 자원 해제','java','code_error','implementation',
    { tmpl:'파일·DB 커넥션·소켓을 사용 후 {{1}} 하지 않으면 자원 누수가 발생한다.',
      ans:[{idx:1,answers:['close','닫기','해제'],synonyms:['종료','클로즈']}] },
    { tmpl:'Java 7+ 에서는 {{1}} 구문으로 AutoCloseable 자원을 자동 해제한다.',
      ans:[{idx:1,answers:['try-with-resources'],synonyms:['try with resources','자동해제']}] },
    '중'],
  ['IMP-CE-03','해제된 자원 사용','c','code_error','implementation',
    { tmpl:'free() 된 포인터를 재사용하면 {{1}} 취약점으로 임의 코드 실행이 가능하다.',
      ans:[{idx:1,answers:['Use After Free','UAF'],synonyms:['use-after-free','해제 후 사용']}] },
    { tmpl:'해제 직후 포인터에 {{1}}을 대입해 재사용을 차단하는 게 기본 방어다.',
      ans:[{idx:1,answers:['NULL','0'],synonyms:['널','nullptr']}] },
    '상'],
  ['IMP-CE-04','초기화되지 않은 변수 사용','c','code_error','implementation',
    { tmpl:'스택 변수 초기화 없이 읽으면 {{1}} 값이 노출되어 정보 유출이 될 수 있다.',
      ans:[{idx:1,answers:['garbage','쓰레기'],synonyms:['임의값','uninit']}] },
    { tmpl:'모든 지역 변수는 선언 즉시 {{1}} 으로 초기화하거나 calloc 으로 0-초기화한다.',
      ans:[{idx:1,answers:['0','기본값'],synonyms:['zero','영']}] },
    '중'],
  ['IMP-CE-05','신뢰할 수 없는 데이터의 역직렬화','java','code_error','implementation',
    { tmpl:'외부 입력을 Java {{1}} 로 역직렬화하면 임의 객체 생성으로 RCE에 이를 수 있다.',
      ans:[{idx:1,answers:['ObjectInputStream','readObject'],synonyms:['object input stream']}] },
    { tmpl:'대안으로 JSON 파서({{1}}) 같은 데이터 포맷을 사용하고 허용 클래스 화이트리스트를 구성한다.',
      ans:[{idx:1,answers:['Jackson','Gson'],synonyms:['jackson','gson']}] },
    '상'],
  ['IMP-EN-01','잘못된 세션에 의한 데이터 정보 노출','java','encapsulation','implementation',
    { tmpl:'요청별로 새로 생성해야 하는 데이터를 {{1}} 변수에 저장하면 다른 사용자 세션에 노출될 수 있다.',
      ans:[{idx:1,answers:['static','클래스'],synonyms:['스태틱','정적']}] },
    { tmpl:'요청 데이터는 {{1}} 범위에 유지하고 ThreadLocal 사용 시에는 사용 후 remove 로 정리한다.',
      ans:[{idx:1,answers:['request','요청'],synonyms:['요청별','스코프']}] },
    '상'],
  ['IMP-EN-02','제거되지 않고 남은 디버그 코드','java','encapsulation','implementation',
    { tmpl:'배포 전 {{1}} 이나 console.log, 개발자 툴바 설정은 반드시 제거해야 한다.',
      ans:[{idx:1,answers:['System.out.println','println','print'],synonyms:['프린트']}] },
    { tmpl:'프로파일을 {{1}} 와 dev 로 분리해 디버그 설정이 프로덕션에 들어가지 않게 한다.',
      ans:[{idx:1,answers:['prod','production'],synonyms:['운영']}] },
    '하'],
  ['IMP-EN-03','Public 메소드부터 반환된 Private 배열','java','encapsulation','implementation',
    { tmpl:'public 메소드가 내부 private 배열을 그대로 반환하면 호출자가 {{1}} 할 수 있어 캡슐화가 깨진다.',
      ans:[{idx:1,answers:['수정','modify'],synonyms:['변경','mutate']}] },
    { tmpl:'반환할 때는 Arrays.{{1}} 로 복사본을 돌려주어야 외부 수정으로부터 보호된다.',
      ans:[{idx:1,answers:['copyOf','clone'],synonyms:['copy of']}] },
    '중'],
  ['IMP-EN-04','Private 배열에 Public 데이터 할당','java','encapsulation','implementation',
    { tmpl:'setter 가 외부에서 전달받은 배열을 그대로 저장하면 외부에서 {{1}}을 계속 유지할 수 있다.',
      ans:[{idx:1,answers:['참조','reference'],synonyms:['레퍼런스']}] },
    { tmpl:'setter 에서는 Arrays.{{1}} 로 깊은 복사 후 저장해 내부 상태를 보호한다.',
      ans:[{idx:1,answers:['copyOf','clone'],synonyms:['copy of']}] },
    '중'],
  ['IMP-AA-01','DNS lookup에 의존한 보안결정','java','api_abuse','implementation',
    { tmpl:'IP 역조회나 DNS 이름으로 권한을 결정하면 {{1}} 스푸핑 공격에 취약하다.',
      ans:[{idx:1,answers:['DNS','dns'],synonyms:['도메인']}] },
    { tmpl:'인증은 DNS가 아닌 TLS 인증서·{{1}} 기반 식별로 수행해야 한다.',
      ans:[{idx:1,answers:['토큰','token'],synonyms:['JWT','인증 토큰']}] },
    '상'],
  ['IMP-AA-02','취약한 API 사용','java','api_abuse','implementation',
    { tmpl:'Java 의 {{1}} 메소드는 플랫폼 기본 문자셋을 사용해 환경에 따라 다르게 동작하므로 사용을 피한다.',
      ans:[{idx:1,answers:['String.getBytes()','new String(byte[])'],synonyms:['getbytes']}] },
    { tmpl:'대신 명시적으로 {{1}}(UTF-8) 처럼 인코딩을 지정해야 한다.',
      ans:[{idx:1,answers:['StandardCharsets.UTF_8','UTF-8'],synonyms:['utf8','utf-8']}] },
    '중'],
];

// 마크다운 body, reference, explanation 생성 헬퍼
function buildQuestion(chapter, qIdx, qData, [code, name, lang, cat, stage, , , difficulty]) {
  const suffix = qIdx === 0 ? 'a' : 'b';
  const weakness_code = `${code}-BLANK-${suffix.toUpperCase()}`;
  const topicExpl = EXPLANATIONS[code] || '';

  // 정답 블록 — 사용자가 채점 후 즉시 참고할 수 있도록 첫 줄에 표시
  const correctSummary = qData.ans
    .map(a => `  #${a.idx} = ${(a.answers || []).join(' / ') || '-'}`)
    .join('\n');
  const explanation = topicExpl
    ? `정답:\n${correctSummary}\n\n해설:\n${topicExpl}`
    : `정답:\n${correctSummary}`;

  return {
    question_type: 'blank',
    weakness_category: cat,
    weakness_code,
    chapter_code: code,     // 원본 챕터 코드 (예: DSG-IV-01) — 학습자료 상세에서 필터링에 사용
    weakness_name_ko: name,
    language: lang,
    difficulty: difficulty || '중',
    body: `[${stage === 'design' ? '설계' : '구현'} · ${name}]\n아래 빈칸을 채우시오.`,
    blank_template: qData.tmpl,
    blank_answers: qData.ans,
    explanation,
    reference: `진단가이드 §${name}`,
    tags: ['blank', stage, 'auto-seed'],
    is_active: true,
  };
}

const questions = [];
for (const row of TOPICS) {
  const [, , , , stage, q1, q2] = row;
  questions.push(buildQuestion(row[0], 0, q1, row));
  questions.push(buildQuestion(row[0], 1, q2, row));
}

// scripts/seed/ 위치 → 저장소 루트 기준 상대 경로 1단계 더 깊음
const outPath = writeSeedJson('kisa-module/seed/blank-questions.json', { questions });

console.log(`✅ 생성 완료: ${questions.length}문제 → ${outPath}`);
console.log(`   stages: design=${TOPICS.filter(t => t[4]==='design').length*2}, implementation=${TOPICS.filter(t => t[4]==='implementation').length*2}`);
